### ISSUE TITLE
[FEAT] B_USER - 회원가입 기능 구현

### ISSUE THREAD

**Issue by TirTir** [TirTir/Entry-BE-Assignment#1]
## 📖 Describe
> 유저 엔티티 정의 및 회원가입 로직 구현

## ✅ TODO
- [x] User 엔티티 정의
- [x] 유효성 검사
- [x] 비밀번호 암호화 (bcrypt)
- [x] 사용자 정보 저장
