### ISSUE TITLE
[FEAT] B_gRPC JWT 검증을 통한 인증 구현

### ISSUE THREAD

**Issue by TirTir** [TirTir/Entry-BE-Assignment#11]
## 📖 Describe
> JWT 검증을 통한 gRPC 인증 구현

## ✅ TODO
- [x] gRPC 클라이언트 구현
- [x] gRPC 서버 구현
- [x] 응답 형식 작성
- [x] 토큰이 유효한 경우 사용자 정보( userId, username, role) 반환

## 참고
> [참고자료](https://curiousjinan.tistory.com/entry/springboot3-grpc)
> [참고자료](https://velog.io/@chb1828/Spring-boot%EB%A1%9C-Grpc%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EC%9E%90)
